export const countryList = {
  australia: {
    country: "australia",
    cities: [
      "melbourne",
      "sydney",
      "brisbane",
      "perth",
      "adelaide",
      "canberra",
      "hobart",
      "currie",
      "geelong",
      "launceston",
      "wagga wagga",
      "newcastle",
    ],
  },
  austria: {
    country: "austria",
    cities: [
      "wien",
      "vienna",
      "graz",
      "linz",
      "salzburg",
      "innsbruck",
      "klagenfurt",
      "villach",
      "weis",
      "st pölten",
      "dornbirn",
    ],
  },
  belgium: {
    country: "belgium",
    cities: [
      "brussels",
      "antwerp",
      "ghent",
      "liege",
      "bruges",
      "namur",
      "charleroi",
      "luxembourg",
    ],
  },
  canada: {
    country: "canada",
    cities: ["ottawa", "toronto"],
  },
  denmark: {
    country: "denmark",
    cities: ["københavn", "kopenhagen"],
  },
  finland: {
    country: "finland",
    cities: ["helsinki", "espoo", "vantaa", "tampere", "turku"],
  },
  france: {
    country: "france",
    cities: ["paris", "marseille"],
  },
  germany: {
    county: "germany",
    cities: [
      "mannheim",
      "karlsruhe",
      "berlin",
      "hamburg",
      "bremen",
      "gütersloh",
      "hildesheim",
      "siegen",
      "münchen",
      "köln",
      "frankfurt am main",
      "düsseldorf",
      "moers",
      "trier",
      "salzgitter",
      "bremerhaven",
      "recklingshausen",
      "jena",
      "remscheid",
      "koblenz",
      "reutlingen",
      "göttingen",
      "wolfsburg",
      "pforzheim",
      "ulm",
      "heilbronn",
      "würzburg",
      "fürth",
      "offenbach am main",
      "ingolstadt",
      "paderborn",
      "regensburg",
      "neuss",
      "herne",
      "heidelberg",
      "darmstadt",
      "solingen",
      "leverkusen",
      "osnabrück",
      "oldenburg",
      "ludwigshafen am rhein",
      "hamm",
      "stuttgart",
      "saarbrücken",
      "postdam",
      "Berlin",
      "bochum",
      "stuttgart",
      "frankfurt",
      "leipzig",
      "dortmund",
      "essen",
      "hannover",
      "nürnberg",
      "duisburg",
      "wuppertal",
      "bielefeld",
      "bonn",
      "münster",
      "augsburg",
      "wiesbaden",
      "mönchengladbach",
      "gelsenkirchen",
      "aachen",
      "braunschweig",
      "kiel",
      "chemnitz",
      "halle",
      "magdeburg",
      "freiburg",
      "krefeld",
      "mainz",
      "lübeck",
      "erfurt",
      "oberhausen",
      "rostock",
      "kassel",
      "hagen",
      "potsdam",
      "mühlheim am rhein",
      "sollingen",
      "bottrop",
      "erlangen",
      "bergisch gladbach",
      "amsterdam",
      "rastatt",
      "butzbach",
      "fulda",
    ],
  },
  india: {
    country: "india",
    cities: [
      "delhi",
      "new delhi",
      "mumbai",
      "pune",
      "bangalore",
      "hyderabad",
      "chennai",
      "kolkata",
      "ahmedabad",
      "surat",
      "bengaluru",
      "kochi",
      "indore",
    ],
  },
  ireland: {
    country: "ireland",
    cities: ["dublin"],
  },
  italy: {
    country: "italy",
    cities: [
      "rom",
      "rome",
      "milan",
      "naples",
      "turin",
      "palermo",
      "genoa",
      "bologna",
      "florence",
      "cagliari",
      "catania",
    ],
  },
  luxembourg: {
    country: "luxembourg",
    cities: ["luxembourg"],
  },
  netherlands: {
    county: "netherlands",
    cities: [
      "amsterdam",
      "rotterdam",
      "the hague",
      "utrecht",
      "eindhoven",
      "groningen",
      "tilburg",
      "almere",
      "breda",
      "nijmengen",
      "apeldoorn",
      "haarlem",
      "arnhem",
      "enschede",
      "amersfoort",
      "zaanstad",
      "haarlemmermeer",
      "den bosch",
      "zwolle",
      "leiden",
    ],
  },
  new_zealand: {
    country: "new zealand",
    cities: ["auckland", "wellington"],
  },
  norway: {
    country: "norway",
    cities: ["oslo"],
  },
  poland: {
    country: "poland",
    cities: ["warsaw"],
  },
  portugal: {
    country: "portugal",
    cities: ["lisbon"],
  },
  spain: {
    country: "spain",
    cities: ["madrid", "barcelona"],
  },
  sweden: {
    country: "sweden",
    cities: ["stockholm"],
  },
  switzerland: {
    country: "switzerland",
    cities: ["zürich", "zurich"],
  },
  usa: {
    county: "usa",
    cities: [
      "new york city",
      "los angeles",
      "chicago",
      "houston",
      "phoenix",
      "san antonio",
      "philadelphia",
      "san diego",
      "dallas",
      "san jose",
      "fort worth",
      "jacksonville",
      "charlotte",
      "indianapolis",
      "san francisco",
      "seatle",
      "denver",
      "washington",
      "nashville",
      "oklahoma city",
      "el paso",
      "boston",
      "portland",
      "las vegas",
      "detroit",
      "memphis",
      "louisville",
      "baltimore",
      "milwaukee",
      "albuquerque",
      "sacramento",
      "kansas city",
      "colorado",
    ],
  },
  united_kingdom: {
    county: "united kingdom",
    cities: [
      "london",
      "bristol",
      "leeds",
      "liverpool",
      "manchester",
      "birmingham",
      "glasgow",
    ],
  },
};
